"""Initial production-grade schema

Revision ID: 0e51a6425c24
Revises: 
Create Date: 2026-06-09 23:28:13.142829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e51a6425c24'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cyber_crimes',
    sa.Column('auth_id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('crimeCategory', sa.String(length=100), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('date_of_incident', sa.Date(), nullable=False),
    sa.Column('time', sa.String(length=50), nullable=True),
    sa.Column('IpAddress', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('digitalEvidence', sa.Text(), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('contact_number', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('relation', sa.String(length=50), nullable=True),
    sa.Column('policeStation', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('auth_id')
    )
    op.create_table('domestic_forms',
    sa.Column('auth_id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('registeration_type', sa.String(length=100), nullable=False),
    sa.Column('reporter_details', sa.Text(), nullable=False),
    sa.Column('reporter_age', sa.Integer(), nullable=True),
    sa.Column('reporter_gender', sa.String(length=10), nullable=True),
    sa.Column('reporter_contact', sa.String(length=15), nullable=True),
    sa.Column('reporter_Emailaddress', sa.String(length=255), nullable=False),
    sa.Column('reporter_native_place', sa.String(length=255), nullable=False),
    sa.Column('employer_name', sa.String(length=100), nullable=False),
    sa.Column('employer_contact', sa.String(length=15), nullable=False),
    sa.Column('employer_relations', sa.String(length=100), nullable=False),
    sa.Column('employer_address', sa.String(length=255), nullable=False),
    sa.Column('documentation', sa.Text(), nullable=True),
    sa.Column('duration_of_stay', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('auth_id')
    )
    op.create_table('lost_items',
    sa.Column('auth_id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('placeofloss', sa.String(length=255), nullable=True),
    sa.Column('loss_datetime', sa.DateTime(), nullable=False),
    sa.Column('owner_name', sa.String(length=100), nullable=False),
    sa.Column('contact_number', sa.String(length=15), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('document_type', sa.Text(), nullable=False),
    sa.Column('police_station', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('auth_id')
    )
    op.create_table('missing_persons',
    sa.Column('auth_id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('Fullname', sa.String(length=100), nullable=False),
    sa.Column('Numberofperson', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('fathername', sa.String(length=100), nullable=False),
    sa.Column('relation', sa.String(length=100), nullable=False),
    sa.Column('lastknownlocation', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('yearofbirth', sa.Integer(), nullable=False),
    sa.Column('agefrom', sa.Integer(), nullable=False),
    sa.Column('ageto', sa.Integer(), nullable=False),
    sa.Column('bodybuild', sa.String(length=100), nullable=False),
    sa.Column('complexion', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('incidentReport', sa.Text(), nullable=False),
    sa.Column('detailsLastseen', sa.Text(), nullable=False),
    sa.Column('datetimelastseen', sa.DateTime(), nullable=False),
    sa.Column('complainant_name', sa.Text(), nullable=False),
    sa.Column('relationwithMissingperson', sa.String(length=100), nullable=False),
    sa.Column('complainant_address', sa.String(length=255), nullable=False),
    sa.Column('complainant_contact', sa.String(length=15), nullable=False),
    sa.Column('alternate_contact', sa.String(length=15), nullable=False),
    sa.Column('emailaddress', sa.String(length=255), nullable=False),
    sa.Column('anyotherdetails', sa.Text(), nullable=False),
    sa.Column('policestation', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('upload_document', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('auth_id')
    )
    op.create_table('mv_thefts',
    sa.Column('auth_id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('vehicleDetails', sa.Text(), nullable=False),
    sa.Column('owner_details', sa.Text(), nullable=False),
    sa.Column('date_of_theft', sa.Date(), nullable=False),
    sa.Column('timeoftheft', sa.String(length=50), nullable=False),
    sa.Column('location_of_theft', sa.String(length=255), nullable=False),
    sa.Column('previous_fir_details', sa.Text(), nullable=False),
    sa.Column('upload_document', sa.Text(), nullable=True),
    sa.Column('police_station', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('auth_id')
    )
    op.create_table('rape_cases',
    sa.Column('auth_id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('victim_name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('incidentDetails', sa.Text(), nullable=False),
    sa.Column('perpetratorDetails', sa.Text(), nullable=False),
    sa.Column('location_of_incident', sa.String(length=255), nullable=False),
    sa.Column('date_of_incident', sa.Date(), nullable=False),
    sa.Column('time_of_incident', sa.String(length=50), nullable=False),
    sa.Column('upload_document', sa.Text(), nullable=True),
    sa.Column('informant_details', sa.Text(), nullable=False),
    sa.Column('police_station', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('auth_id')
    )
    op.create_table('sos_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('location_address', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('incident_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sos_reports_clerk_user_id'), 'sos_reports', ['clerk_user_id'], unique=False)
    op.create_table('theft_efirs',
    sa.Column('auth_id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('incident_description', sa.Text(), nullable=False),
    sa.Column('date_of_theft', sa.Date(), nullable=False),
    sa.Column('financial_impact', sa.Text(), nullable=True),
    sa.Column('witness_information', sa.Text(), nullable=True),
    sa.Column('complainant_details', sa.Text(), nullable=True),
    sa.Column('upload_document', sa.Text(), nullable=True),
    sa.Column('police_station', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('auth_id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('theft_efirs')
    op.drop_index(op.f('ix_sos_reports_clerk_user_id'), table_name='sos_reports')
    op.drop_table('sos_reports')
    op.drop_table('rape_cases')
    op.drop_table('mv_thefts')
    op.drop_table('missing_persons')
    op.drop_table('lost_items')
    op.drop_table('domestic_forms')
    op.drop_table('cyber_crimes')
    # ### end Alembic commands ###
