"""Initial production-grade schema

Revision ID: 0e51a6425c24
Revises: 
Create Date: 2026-06-09 23:28:13.142829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e51a6425c24'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cyber_crimes',
    sa.Column('auth_id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('crimeCategory', sa.String(length=100), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('date_of_incident', sa.Date(), nullable=False),
    sa.Column('time', sa.String(length=50), nullable=True),
    sa.Column('IpAddress', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('digitalEvidence', sa.Text(), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('contact_number', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('relation', sa.String(length=50), nullable=True),
    sa.Column('policeStation', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('auth_id')
    )
    op.create_table('domestic_forms',
    sa.Column('auth_id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('registeration_type', sa.String(length=100), nullable=False),
    sa.Column('reporter_details', sa.Text(), nullable=False),
    sa.Column('reporter_age', sa.Integer(), nullable=True),
    sa.Column('reporter_gender', sa.String(length=10), nullable=True),
    sa.Column('reporter_contact', sa.String(length=15), nullable=True),
    sa.Column('reporter_Emailaddress', sa.String(length=255), nullable=False),
    sa.Column('reporter_native_place', sa.String(length=255), nullable=False),
    sa.Column('employer_name', sa.String(length=100), nullable=False),
    sa.Column('employer_contact', sa.String(length=15), nullable=False),
    sa.Column('employer_relations', sa.String(length=100), nullable=False),
    sa.Column('employer_address', sa.String(length=255), nullable=False),
    sa.Column('documentation', sa.Text(), nullable=True),
    sa.Column('duration_of_stay', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('auth_id')
    )
    op.create_table('lost_items',
    sa.Column('auth_id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('placeofloss', sa.String(length=255), nullable=True),
    sa.Column('loss_datetime', sa.DateTime(), nullable=False),
    sa.Column('owner_name', sa.String(length=100), nullable=False),
    sa.Column('contact_number', sa.String(length=15), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('document_type', sa.Text(), nullable=False),
    sa.Column('police_station', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('auth_id')
    )
    op.create_table('missing_persons',
    sa.Column('auth_id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('Fullname', sa.String(length=100), nullable=False),
    sa.Column('Numberofperson', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=False),
    sa.Column('fathername', sa.String(length=100), nullable=False),
    sa.Column('relation', sa.String(length=100), nullable=False),
    sa.Column('lastknownlocation', sa.String(length=255), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('yearofbirth', sa.Integer(), nullable=False),
    sa.Column('agefrom', sa.Integer(), nullable=False),
    sa.Column('ageto', sa.Integer(), nullable=False),
    sa.Column('bodybuild', sa.String(length=100), nullable=False),
    sa.Column('complexion', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('incidentReport', sa.Text(), nullable=False),
    sa.Column('detailsLastseen', sa.Text(), nullable=False),
    sa.Column('datetimelastseen', sa.DateTime(), nullable=False),
    sa.Column('complainant_name', sa.Text(), nullable=False),
    sa.Column('relationwithMissingperson', sa.String(length=100), nullable=False),
    sa.Column('complainant_address', sa.String(length=255), nullable=False),
    sa.Column('complainant_contact', sa.String(length=15), nullable=False),
    sa.Column('alternate_contact', sa.String(length=15), nullable=False),
    sa.Column('emailaddress', sa.String(length=255), nullable=False),
    sa.Column('anyotherdetails', sa.Text(), nullable=False),
    sa.Column('policestation', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('upload_document', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('auth_id')
    )
    op.create_table('mv_thefts',
    sa.Column('auth_id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('vehicleDetails', sa.Text(), nullable=False),
    sa.Column('owner_details', sa.Text(), nullable=False),
    sa.Column('date_of_theft', sa.Date(), nullable=False),
    sa.Column('timeoftheft', sa.String(length=50), nullable=False),
    sa.Column('location_of_theft', sa.String(length=255), nullable=False),
    sa.Column('previous_fir_details', sa.Text(), nullable=False),
    sa.Column('upload_document', sa.Text(), nullable=True),
    sa.Column('police_station', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('auth_id')
    )
    op.create_table('rape_cases',
    sa.Column('auth_id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('victim_name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('incidentDetails', sa.Text(), nullable=False),
    sa.Column('perpetratorDetails', sa.Text(), nullable=False),
    sa.Column('location_of_incident', sa.String(length=255), nullable=False),
    sa.Column('date_of_incident', sa.Date(), nullable=False),
    sa.Column('time_of_incident', sa.String(length=50), nullable=False),
    sa.Column('upload_document', sa.Text(), nullable=True),
    sa.Column('informant_details', sa.Text(), nullable=False),
    sa.Column('police_station', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('auth_id')
    )
    op.create_table('sos_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('location_address', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('incident_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sos_reports_clerk_user_id'), 'sos_reports', ['clerk_user_id'], unique=False)
    op.create_table('theft_efirs',
    sa.Column('auth_id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('incident_description', sa.Text(), nullable=False),
    sa.Column('date_of_theft', sa.Date(), nullable=False),
    sa.Column('financial_impact', sa.Text(), nullable=True),
    sa.Column('witness_information', sa.Text(), nullable=True),
    sa.Column('complainant_details', sa.Text(), nullable=True),
    sa.Column('upload_document', sa.Text(), nullable=True),
    sa.Column('police_station', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('auth_id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.drop_table('crime_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crime_data',
    sa.Column('col_0', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('state_ut', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('district', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('year', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('murder', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('attempt_to_murder', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('culpable_homicide_not_amounting_to_murder', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rape', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('custodial_rape', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('other_rape', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('kidnapping_abduction', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('kidnapping_and_abduction_of_women_and_girls', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('kidnapping_and_abduction_of_others', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dacoity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('preparation_and_assembly_for_dacoity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('robbery', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('burglary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('theft', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('auto_theft', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('other_theft', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('riots', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('criminal_breach_of_trust', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cheating', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('counterfeiting', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('arson', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hurt_grevious_hurt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dowry_deaths', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('assault_on_women_with_intent_to_outrage_her_modesty', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('insult_to_modesty_of_women', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cruelty_by_husband_or_his_relatives', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('importation_of_girls_from_foreign_countries', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('causing_death_by_negligence', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('other_ipc_crimes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('total_ipc_crimes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('attempt_to_commit_murder', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('attempt_to_commit_culpable_homicide', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('custodial_gang_rape', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('custodial_other_rape', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rape_other_than_custodial', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rape_gang_rape', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rape_others', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('attempt_to_commit_rape', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('kidnapping_abduction_total', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('kidnapping_abduction_in_order_to_murder', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('kidnapping_for_ransom', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('kidnapping_abduction_of_women_to_compel_her_for_marriage', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('other_kidnapping', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dacoity_with_murder', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('other_dacoity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('making_preparation_and_assembly_for_committing_dacoity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('criminal_trespass_burglary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('criminal_trespass_or_burglary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('house_trespass_house_breaking', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('other_thefts', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('unlawful_assembly', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('riots_communal', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('riots_industrial', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('riots_political', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('riots_caste_conflict', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('riots_sc_sts_vs_non_scs_sts', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('riots_other_caste_conflict', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('riots_agrarian', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('riots_students', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('riots_sectarian', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('riots_others', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('forgery', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('counterfeit_offences_related_to_counterfeit_coin', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('counterfeiting_government_stamp', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('counterfeit_currency_bank_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('counterfeiting_currency_notes_bank_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('using_forged_or_counterfeiting_currency_bank_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('possession_of_forged_or_counterfeiting_currency_bank_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('making_or_possessing_materials_for_forged_currency_bank_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('making_or_using_documents_resembling_currency', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('grievous_hurt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hurt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('acid_attack', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('attempt_to_acid_attack', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sexual_harassment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('assault_or_use_of_criminal_force_to_women_with_intent_to_disrob', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('voyeurism', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stalking', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('other_assault_on_women', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('insult_to_the_modesty_of_women', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('at_office_premises', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('other_places_related_to_work', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('in_public_transport_system', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('places_other_than_231_232_233', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('importation_of_girls_from_foreign_country', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('deaths_due_to_negligent_driving_act', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('deaths_due_to_other_causes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('offences_against_state', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sedition', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('other_offences_against_state', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('offences_promoting_enmity_between_different_groups', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('promoting_enmity_between_different_groups', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('imputation_assertions_prejudicial_to_national_integration', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('extortion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('disclosure_of_identity_of_victims', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('incidence_of_rash_driving', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('humantrafficking', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('unnatural_offence', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('total_cognizable_ipc_crimes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('district_ut', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('theft_efirs')
    op.drop_index(op.f('ix_sos_reports_clerk_user_id'), table_name='sos_reports')
    op.drop_table('sos_reports')
    op.drop_table('rape_cases')
    op.drop_table('mv_thefts')
    op.drop_table('missing_persons')
    op.drop_table('lost_items')
    op.drop_table('domestic_forms')
    op.drop_table('cyber_crimes')
    # ### end Alembic commands ###
