"""Add crime_data table

Revision ID: 27a0fc921a5a
Revises: 0e51a6425c24
Create Date: 2026-06-12 15:56:46.948386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27a0fc921a5a'
down_revision: Union[str, Sequence[str], None] = '0e51a6425c24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crime_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state_ut', sa.String(length=255), nullable=True),
    sa.Column('district', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('murder', sa.Integer(), nullable=True),
    sa.Column('attempt_to_murder', sa.Integer(), nullable=True),
    sa.Column('culpable_homicide_not_amounting_to_murder', sa.Integer(), nullable=True),
    sa.Column('rape', sa.Integer(), nullable=True),
    sa.Column('custodial_rape', sa.Integer(), nullable=True),
    sa.Column('other_rape', sa.Integer(), nullable=True),
    sa.Column('kidnapping_abduction', sa.Integer(), nullable=True),
    sa.Column('kidnapping_and_abduction_of_women_and_girls', sa.Integer(), nullable=True),
    sa.Column('kidnapping_and_abduction_of_others', sa.Integer(), nullable=True),
    sa.Column('dacoity', sa.Integer(), nullable=True),
    sa.Column('preparation_and_assembly_for_dacoity', sa.Integer(), nullable=True),
    sa.Column('robbery', sa.Integer(), nullable=True),
    sa.Column('burglary', sa.Integer(), nullable=True),
    sa.Column('theft', sa.Integer(), nullable=True),
    sa.Column('auto_theft', sa.Integer(), nullable=True),
    sa.Column('other_theft', sa.Integer(), nullable=True),
    sa.Column('riots', sa.Integer(), nullable=True),
    sa.Column('criminal_breach_of_trust', sa.Integer(), nullable=True),
    sa.Column('cheating', sa.Integer(), nullable=True),
    sa.Column('counterfeiting', sa.Integer(), nullable=True),
    sa.Column('arson', sa.Integer(), nullable=True),
    sa.Column('hurt_grevious_hurt', sa.Integer(), nullable=True),
    sa.Column('dowry_deaths', sa.Integer(), nullable=True),
    sa.Column('assault_on_women_with_intent_to_outrage_her_modesty', sa.Integer(), nullable=True),
    sa.Column('insult_to_modesty_of_women', sa.Integer(), nullable=True),
    sa.Column('cruelty_by_husband_or_his_relatives', sa.Integer(), nullable=True),
    sa.Column('importation_of_girls_from_foreign_countries', sa.Integer(), nullable=True),
    sa.Column('causing_death_by_negligence', sa.Integer(), nullable=True),
    sa.Column('other_ipc_crimes', sa.Integer(), nullable=True),
    sa.Column('total_ipc_crimes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crime_data_district'), 'crime_data', ['district'], unique=False)
    op.create_index(op.f('ix_crime_data_state_ut'), 'crime_data', ['state_ut'], unique=False)
    op.create_index(op.f('ix_crime_data_year'), 'crime_data', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crime_data_year'), table_name='crime_data')
    op.drop_index(op.f('ix_crime_data_state_ut'), table_name='crime_data')
    op.drop_index(op.f('ix_crime_data_district'), table_name='crime_data')
    op.drop_table('crime_data')
    # ### end Alembic commands ###
