"""fix police_station fields

Revision ID: bd7673fdbeb7
Revises: 27a0fc921a5a
Create Date: 2026-06-17 18:53:47.622539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd7673fdbeb7'
down_revision: Union[str, Sequence[str], None] = '27a0fc921a5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cyber_crimes', sa.Column('police_station', sa.String(length=100), nullable=False))
    op.drop_column('cyber_crimes', 'policeStation')
    op.add_column('domestic_forms', sa.Column('police_station', sa.String(length=100), nullable=False))
    op.add_column('missing_persons', sa.Column('police_station', sa.String(length=100), nullable=False))
    op.drop_column('missing_persons', 'policestation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missing_persons', sa.Column('policestation', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('missing_persons', 'police_station')
    op.drop_column('domestic_forms', 'police_station')
    op.add_column('cyber_crimes', sa.Column('policeStation', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('cyber_crimes', 'police_station')
    # ### end Alembic commands ###
